# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de8957f5fec848a1995a9e50f177ced2"
name = "wish-list"
handle = "wish-list-26"
application_url = "https://mailman-framework-roy-tend.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testingwishlist.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://mailman-framework-roy-tend.trycloudflare.com/auth/callback",
  "https://mailman-framework-roy-tend.trycloudflare.com/auth/shopify/callback",
  "https://mailman-framework-roy-tend.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://mailman-framework-roy-tend.trycloudflare.com/app/proxy"
subpath = "proxytest"
prefix = "apps"

[pos]
embedded = false
