# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "wish-list"
client_id = "9ad892ecbfedb83066ecadf4409301cc"
application_url = "https://enhancing-identifier-april-bind.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://enhancing-identifier-april-bind.trycloudflare.com/auth/callback",
  "https://enhancing-identifier-april-bind.trycloudflare.com/auth/shopify/callback",
  "https://enhancing-identifier-april-bind.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "wish-list-alpha.myshopify.com"
