# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "648015b8ba04d0a04710875cb32a41be"
name = "Wishify"
handle = "wishifylist"
application_url = "https://vital-wish-list-c86fce13cbd9.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "testingwishlist.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://vital-wish-list-c86fce13cbd9.herokuapp.com/auth/callback",
  "https://vital-wish-list-c86fce13cbd9.herokuapp.com/auth/shopify/callback",
  "https://vital-wish-list-c86fce13cbd9.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
  uri = "https://vital-wish-list-c86fce13cbd9.herokuapp.com/webhooks"

[pos]
embedded = false
