# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "wish-list"
client_id = "de8957f5fec848a1995a9e50f177ced2"
application_url = "https://rg-fw-earning-regular.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rg-fw-earning-regular.trycloudflare.com/auth/callback",
  "https://rg-fw-earning-regular.trycloudflare.com/auth/shopify/callback",
  "https://rg-fw-earning-regular.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testingwishlist.myshopify.com"
