# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "648015b8ba04d0a04710875cb32a41be"
name = "Wish List"
handle = "wish-list-34"
application_url = "https://wish-list-shopify-bc95606b6963.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "testingwishlist.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://wish-list-shopify-bc95606b6963.herokuapp.com/auth/callback",
  "https://wish-list-shopify-bc95606b6963.herokuapp.com/auth/shopify/callback",
  "https://wish-list-shopify-bc95606b6963.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
